GET http://localhost:5000/login/check-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJxdzIyMyIsImVtYWlsIjoiam9zZWZhQGdtYWlsLmNvbSIsImlhdCI6MTcyNzQyODk3MywiZXhwIjoxNzI3NDI5MDMzfQ.Q_90oVkqZSZXGi2bvTzboWhxtiEDJZFAPq4nPRaen_Q